Repository trimstray/the-book-of-secret-knowledge, pull requests merged in 2018-12, with the labels that each got.

#6 added atop
  README.md
Labels: Status: Review Needed, Type: Enhancement

#9 fixed security
  README.md
Labels: Status: Review Needed, Type: Bug

#11 Added explainshell and exploitdb
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement

#16 Fix Nginx website link
  README.md
Labels: Status: Review Needed, Type: Bug

#19 Added gobuster to Network section
  README.md
Labels: Status: Review Needed, Type: Enhancement

#22 Pingdom Tools
  README.md
Labels: Status: Review Needed, Type: Enhancement

#23 Added Lynx to Network Chapter
  README.md
Labels: Status: Review Needed, Type: Enhancement

#25 Add Repl.it to README
  README.md
Labels: Status: Review Needed, Type: Enhancement

#28 Adding tldr
  README.md
Labels: Status: Review Needed, Type: Enhancement

#29 Added SSL Check to the list
  README.md
Labels: Status: Review Needed, Type: Enhancement

#30 added vscode to text editors
  README.md
Labels: Status: Review Needed, Type: Enhancement

#32 Add dkimvalidator.com under mail section (and other important tools).
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement

#33 Added `ssh -tt`
  README.md
Labels: Status: Review Needed, Type: Enhancement

#37 Added PageSpeed Insights in performance section
  README.md
Labels: Status: Review Needed, Type: Enhancement

#35 Add link to Linux Guide and Hints
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement

#39 Test if the current user is sudo-su'd into this session
  README.md
Labels: Status: Review Needed, Type: Enhancement

#38 Added PbScan in network section
  README.md
Labels: Status: Review Needed, Type: Enhancement

#40 find panic reboots with /usr/bin/last
  README.md
Labels: Status: Review Needed, Type: Enhancement

#41 Added 'GDB PEDA', 'Microcorruption', and 'Crackmes'
  README.md
Labels: Status: Review Needed, Type: Enhancement

#45 Added CodeSandbox
  README.md
Labels: Status: Review Needed, Type: Enhancement
