Repository trimstray/the-book-of-secret-knowledge, pull requests merged in 2019-01, with the labels that each got.

#43 Adding Etherate to 'Networking'
  README.md
Labels: Status: Review Needed, Type: Enhancement

#48 Update README.md
  README.md
Labels: Edited, Status: Accepted, Type: Enhancement

#51 Update README.md
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement

#52 Added reverse engineering - Issue #49
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement

#58 Updated README.md, Added mkcert
  README.md
Labels: Status: Review Needed, Type: Enhancement

#59 Update README.md
  README.md
Labels: Status: Review Needed, Type: Bug

#62 added 'https://1.1.1.1/' website DNS
  README.md
Labels: Status: Review Needed, Type: Enhancement
