Repository trimstray/the-book-of-secret-knowledge, pull requests merged in 2019-04, with the labels that each got.

#82 added traefik tool to 'HTTP(s) Services' chapter
  README.md
Labels: Edited, Status: Review Needed, Type: Feature

#83 Simple bash filewatching with MAIL variables
  README.md
Labels: Status: Review Needed, Type: Feature

#84 Add Osmedeus
  README.md
Labels: Edited, Status: Accepted, Type: Feature

#85 sterilize shell history
  README.md
Labels: Status: Review Needed, Type: Enhancement

#86 Add nnn
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement
