Repository trimstray/the-book-of-secret-knowledge, pull requests merged in 2019-03, with the labels that each got.

#77 Improve documentation
  README.md
Labels: Status: Review Needed, Type: Enhancement

#76 Add Shell Style Guide
  README.md
Labels: Status: Review Needed, Type: Enhancement

#75 Add Performance Co-Pilot
  README.md
Labels: Status: Review Needed, Type: Enhancement

#78 Minor awk tweak
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement

#79 Added Websploit and a few Bounty platforms
  README.md
Labels: Edited, Status: Review Needed, Type: Enhancement

#80 Add tutorial to setup a DNS-over-TLS server
  README.md
Labels: Status: Review Needed, Type: Enhancement

#81 Fixed displayed domain for xip.io from xip.ip
  README.md
Labels: Status: Review Needed, Type: Bug
